### ISSUE TITLE
failed to get current version

### ISSUE THREAD

**Issue by nerdalytics** [joaofnds/asdf-install-latest#1]
Hi,

I created a fish script to solve the same issue, but your solution takes care of ignoring packages and reinstalling packages. Brilliant :)

I tried your tool, and it doesn't seem to work as expected. It seems not finding current version. I wonder if I need to have versions set globally. Except for Golang, and Node.js, I'm not using global versions.

```
asdf-install-latest
[elasticsearch] failed to get current version: exit status 126
[deno] failed to get current version: exit status 126
[pnpm] failed to get current version: exit status 126
[maven] failed to get current version: exit status 126
[nodejs] failed to get current version: no versions found for package 'nodejs'
[python] failed to get current version: exit status 126
[java] failed to get current version: exit status 126
[ruby] failed to get current version: exit status 126
[yarn] failed to get current version: exit status 126
[golang] no updates
reshiming...
```

Running `asdf list` reveals a bunch of installed versions.
```
asdf list
deno
  1.12.0
elasticsearch
  No versions installed
golang
  1.18.3
  1.19.1
  1.19.2
java
  adoptopenjdk-18.0.1+10
maven
  3.8.5
nodejs
  16.14.0
  16.6.1
  16.8.0
  16.9.0
  16.9.1
  17.4.0
  17.6.0
  18.7.0
  lts
pnpm
  6.10.2
  6.12.1
  6.14.3
  6.14.5
  6.14.7
python
  3.10.0
  3.9.6
  3.9.7
ruby
  3.0.2
yarn
  1.22.11
  1.22.17
  1.22.19
```

*Note: Installed your tool via brew.*
```
brew info asdf-install-latest
==> joaofnds/tap/asdf-install-latest: stable 0.0.7
```

**Comment by joaofnds** [comment]
Hello there 👋 Thanks for trying it out!

I guess I never really considered this use case. I think the solution is to get the latest installed (instead of the current) version from the `asdf list` and add a config to skip setting the global version. What do you think?

**Comment by joaofnds** [comment]
released [0.0.8](https://github.com/joaofnds/asdf-install-latest/releases/tag/0.0.8), check it out, it should work for your use case now

I ended up creating a proper config file, so you might have to move ignored packages to the new format if you had any.

```yaml
# ~/.config/ail/config.yml
skip_set_global: true
ignore: []
```

**Comment by nerdalytics** [comment]
Great! Works fine. Now I can retire my shell script :)

**Comment by nerdalytics** [comment]
> Hello there 👋 Thanks for trying it out!
> 
> I guess I never really considered this use case. I think the solution is to get the latest installed (instead of the current) version from the `asdf list` and add a config to skip setting the global version. What do you think?

I see. My use case is different. I install [all] the tools I need in [any of] my projects, but I'm not setting all of them globally available. With two exceptions–cuz I'm lazy I set Go and Node.js globally. The other tools/package become active via local `.tool-versions` file.
